### ISSUE TITLE
请问扫码登陆如何使用？

### ISSUE THREAD

**Issue by Cxyofficial** [Womsxd/mihoyo_login#3]

**Comment by yzyi0320** [comment]
写个bat加个pause防止命令行运行完就关了就行了
python qr_login.py
pause

**Comment by Cxyofficial** [comment]
请问sh可以嘛

**Comment by Womsxd** [comment]
打开一个cmd / powershell / *sh 窗口(只要运行完成后窗口不会自动关闭)，然后执行 运行脚本，用米游社扫码
