### ISSUE TITLE
码扫不上怎么解决

### ISSUE THREAD

**Issue by sykeswzq** [Womsxd/mihoyo_login#5]
用cmd运行后出来的码，用米游社扫，扫不上
![1](https://github.com/Womsxd/mihoyo_login/assets/97281429/f15bf2df-82ae-43a7-a479-55ae4de35214)
@Womsxd @Night-stars-1

**Comment by Womsxd** [comment]
脚本目录下目录下回生成一个 code.png ，和cmd窗口输出的内容是一致的，cmd窗口乱码请扫code.png
或者用[cmder](https://github.com/cmderdev/cmder) / Windows Terminal:[github](https://github.com/microsoft/terminal/) [microsoft store](https://apps.microsoft.com/detail/9n0dx20hk701?rtc=1&hl=zh-cn&gl=CN)

**Comment by sykeswzq** [comment]
> 脚本目录下目录下回生成一个 code.png ，和cmd窗口输出的内容是一致的，cmd窗口乱码请扫code.png 或者用[cmder](https://github.com/cmderdev/cmder) / Windows Terminal:[github](https://github.com/microsoft/terminal/) [microsoft store](https://apps.microsoft.com/detail/9n0dx20hk701?rtc=1&hl=zh-cn&gl=CN)
扫完，出了这个问题
![222](https://github.com/Womsxd/mihoyo_login/assets/97281429/1b22d25e-cbbe-487e-bdbf-61a7673b058a)

**Comment by Womsxd** [comment]
你cookie没抓，或者cookie有问题

**Comment by sykeswzq** [comment]
懂了 我重新抓一下

**Comment by sykeswzq** [comment]
好了 ，感谢！
